# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hank's Blog
email: 253848296@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  The more diligent, the more luckier you are
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shcqupc.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:year/:month/:day/:title/

# other links
twitter_username: chefsh
facebook_username:
github_username:  shcqupc
weibo_username: 
zhihu_username: 
linkedIn_username: 
dribbble_username:

# Build settings
theme: minima
#plugins:
#  - jekyll-feed


description_footer: Posts by Hank.S

# comments
# two ways to comment, only choose one, and use your own short name 
duoshuo_shortname:  
disqus_shortname:  

# statistic analysis 
baidu_tongji_id: be3e55e43bc422ebb6b6d3338abdceb7
google_analytics_id:  # google

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
port: 4001



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/